CREATE TABLE NEW_INFO
(
    ID VARCHAR(60) PRIMARY KEY NOT NULL,
    NAME VARCHAR(60),
    TITLE VARCHAR(100),
    CONTENT VARCHAR(2000)
);
CREATE TABLE T_USER
(
    ID VARCHAR(60) PRIMARY KEY NOT NULL,
    NAME VARCHAR(30),
    AGE INT(11),
    SEX INT(11),
    SUMMARY VARCHAR(200),
    CREATE_USER_ID VARCHAR(60),
    CREATE_TIME DATETIME
);
CREATE TABLE EX_PAY
(
    ID VARCHAR(60) PRIMARY KEY NOT NULL,
    USER_ID VARCHAR(60),
    AMOUNT DECIMAL(10,2)
);
CREATE TABLE EX_ORDER
(
    ID VARCHAR(60) PRIMARY KEY NOT NULL,
    USER_ID VARCHAR(60),
    ORDER_NAME VARCHAR(100),
    amount DECIMAL(10,2)
);